#####
GET http://localhost:8888/api/catalogos

#####
GET http://localhost:8888/api/catalogos/c/prueba_sql
#####
DELETE http://localhost:8888/api/catalogos/delete/8

#####
POST http://localhost:8888/api/catalogos/create
Content-Type:application/json

{
    "codigo":"PRUBSQ1",
    "valor":"borrado temporal",
    "tipo":"prueba_sql"
}