#####
GET http://localhost:8888/api/catalogos?nuPag=0&pagSize=10&sortBy=codigo&sortDir=asc

#####
GET http://localhost:8888/api/catalogos/c/prueba_api
#####
GET http://localhost:8888/api/catalogos/get/PRUBAP2
####
DELETE http://localhost:8888/api/catalogos/delete/NOVAL

#####
POST http://localhost:8888/api/catalogos/create
Content-Type:application/json

{
    "codigo":"TIPPR2",
    "valor":"muebles",
    "tipo":"tipo_proveedor"
}
####
PUT http://localhost:8888/api/catalogos/edit/
Content-Type: application/json

{
    "valor":"api",
    "tipo":"prueba_api edit"
}