#####
GET http://localhost:8888/api/catalogos

#####
GET http://localhost:8888/api/catalogos/c/prueba_api
#####
GET http://localhost:8888/api/catalogos/get/PRUBAP2
#####
DELETE http://localhost:8888/api/catalogos/delete/8

#####
POST http://localhost:8888/api/catalogos/create
Content-Type:application/json

{
    "codigo":"PRUBAP2",
    "valor":"api",
    "tipo":"prueba_api"
}
####
PUT  http://localhost:8888/api/catalogos/edit/PRUBAP2
Content-Type: application/json

{
    "valor":"api",
    "tipo":"prueba_api edit"
}